# Generated by Django 5.1 on 2025-11-17 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('artist', models.CharField(max_length=200)),
                ('album', models.CharField(blank=True, max_length=200, null=True)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='song_covers/')),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='songs/')),
                ('category', models.CharField(choices=[('new_releases', 'New Release'), ('top', 'Top Hits'), ('trend', 'Trending'), ('bhajan', 'Bhajan'), ('punjabi_hits', 'Punjabi'), ('topeng', 'English'), ('indianhits', 'Indian'), ('phonk', 'Phonk')], max_length=50)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('duration', models.CharField(blank=True, max_length=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='Genre',
        ),
        migrations.RemoveField(
            model_name='playlist',
            name='songs',
        ),
        migrations.RemoveField(
            model_name='playlist',
            name='user',
        ),
        migrations.DeleteModel(
            name='Music',
        ),
        migrations.DeleteModel(
            name='Playlist',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
