# Generated by Django 5.1 on 2025-11-17 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_song_delete_genre_remove_playlist_songs_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='category',
            field=models.CharField(choices=[('new_releases', 'New Release'), ('top', 'Top Hits'), ('trend', 'Trending'), ('bhajan', 'Bhajan'), ('punjabi_hits', 'Punjabi'), ('topeng', 'English'), ('indianhits', 'Indian'), ('phonk', 'Phonk'), ('arjit', 'Arjit'), ('drivelist', 'DriveList'), ('genres', 'Genres'), ('honeys', 'Honeys'), ('mixlist', 'MixList'), ('subh1', 'Subh')], max_length=50),
        ),
    ]
